[package]
name = "irmaseal-cli"
description = "Commandline interface for IRMAseal"
version = "0.1.4"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"

[dependencies]
irmaseal-core = { path = "../irmaseal-core" }
ibe = "0.1.3"

tokio = { version = "0.2.5", features = ["rt-threaded", "time"] }
futures = "0.3.4"
qrcode = { version = "0.12.0", default-features = false }
clap = { version = "2.33.0", features = ["yaml"] }
rand = "0.7.3"
arrayvec = { version = "0.5.1", features = ["array-sizes-129-255"] }
serde = "1.0.104"
serde_json = { version = "1.0.57" }
reqwest = { version = "0.10.4", features = ["rustls-tls", "json"], default-features = false }
