[package]
name = "irmaseal-pkg"
version = "0.1.2"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"

[dependencies]
irmaseal-core = "0.1"
ibe = "0.1"
irma = "0.0"

actix-rt = "0.2.2"
actix-web = { version = "1.0.7", default-features = false }
actix-cors = "0.1.0"
arrayref = "0.3.5"
subtle = "2.1.1"
clap = { version = "2.33.0", features = ["yaml"] }
rand = "0.7.0"
serde_json = "1.0.40"
futures = "0.1.28"
