[package]
name = "irmaseal-pkg"
version = "0.1.0"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"

[dependencies]
irmaseal-core = { path = "../irmaseal-core", default-features = false }
ibe = { git = "https://github.com/wassasin/ibe" }
irma = { git = "https://github.com/wassasin/irmars" }

actix-rt = "0.2.2"
actix-web = { version = "1.0.7", default-features = false }
arrayref = "0.3.5"
subtle = "2.1.1"
clap = { version = "2.33.0", features = ["yaml"] }
rand = "0.7.0"
serde_json = "1.0.40"
futures = "0.1.28"